#!/usr/bin/env node
'use strict';

import process from 'node:process';

export default function clean() {
    console.log('removing junk files...');
}

function main() {
    clean();
}

if (import.meta.url === `file:///${process.argv[1]}`) { main(); }
